name: LuckyRabbit
version: '${project.version}'
main: co.RabbitTale.luckyRabbit.LuckyRabbit
api-version: '1.20'
authors: [RabbitTale]
description: Advanced lootbox system with animations
softdepend: [Oraxen, Vault]
commands:
  lootbox:
    description: Main command for LuckyRabbit
    aliases: [lb, luckyrabbit]
    usage: /<command> [subcommand]
permissions:
  luckyrabbit.admin:
    description: Gives access to all admin commands
    default: op
    children:
      luckyrabbit.admin.create: true
      luckyrabbit.admin.delete: true
      luckyrabbit.admin.item: true
      luckyrabbit.admin.place: true
      luckyrabbit.admin.key: true
      luckyrabbit.admin.reload: true
