# LuckyRabbitFoot Configuration
# Version: 1.0.0

# License configuration
license:
  auth-code: "" # Your authorization code
  trial:
    enabled: true
    duration: 3 # Trial duration in days

# Plugin settings
settings:
  language: "en" # Available: en, pl
  debug: false
  save-interval: 300 # Auto-save interval in seconds

# Animation settings
animations:
  particle-update-interval: 5 # Ticks between particle updates
  default-type: "HORIZONTAL" # Default animation type for new lootboxes
  particles:
    enabled: true
    max-per-lootbox: 3

# Supported plugins integration
integrations:
  oraxen:
    enabled: true
  luckperms:
    enabled: true
  economy:
    plugin: "Vault" # Supported: Vault, PlayerPoints
    enabled: true

# API settings
api:
  enabled: true
  url: "https://api.rabbittale.co/lootbox"
  timeout: 5000 # Connection timeout in milliseconds
