name: LuckyRabbitFoot
version: '0.0.1'
main: co.RabbitTale.luckyRabbitFoot.LuckyRabbitFoot
api-version: '1.20'
depend: [Oraxen]
softdepend: [LuckPerms, Vault]
authors: [RabbitTale]
description: Advanced lootbox system with animations and custom rewards
website: https://rabbittale.co

commands:
  lootbox:
    description: Main command for managing lootboxes
    usage: /lootbox
    aliases: [lb, lbox]
    permission: luckyrabbitfoot.use

permissions:
  luckyrabbitfoot.use:
    description: Allows using basic lootbox commands
    default: true
  luckyrabbitfoot.admin:
    description: Gives access to all admin commands
    default: op
    children:
      luckyrabbitfoot.admin.create: true
      luckyrabbitfoot.admin.delete: true
      luckyrabbitfoot.admin.item: true
      luckyrabbitfoot.admin.place: true
      luckyrabbitfoot.admin.key: true
